# -*- coding: utf-8 -*-
"""ECG Feature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAOc3S0f-UkgHdm0FsrpEvHsn4wjT0wI
"""

from pathlib import Path
import os
import requests

# Folder tujuan (lokal)
base_dir = Path.home() / "Documents" / "PhysioNetData" / "ECGID" / "Person_01"
base_dir.mkdir(parents=True, exist_ok=True)
os.chdir(base_dir)

print("Folder aktif:", base_dir)

# URL file ECG-ID Database v1.0.0
base_url = "https://physionet.org/files/ecgiddb/1.0.0/Person_01/"

# Download 1 record: rec_1 (header + data + anotasi)
files_to_download = ["rec_1.hea", "rec_1.dat", "rec_1.atr"]

for fname in files_to_download:
    url = base_url + fname
    response = requests.get(url, timeout=60)
    response.raise_for_status()

    with open(fname, "wb") as f:
        f.write(response.content)

    print(f"Downloaded: {fname}")

print("\nIsi folder:")
for file in Path(".").iterdir():
    print(file.name)

import sys
!{sys.executable} -m pip install -q wfdb matplotlib requests

import wfdb
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, find_peaks

# =====================================
# 1) Load ECG-ID record (10 detik)
# =====================================
record = wfdb.rdrecord("rec_1")
sig = record.p_signal
Fs = record.fs
tm = np.arange(sig.shape[0]) / Fs

ch = 1          # MATLAB ch=2 -> Python index 1
dur = 10
idx = tm <= dur

ecg = sig[idx, ch]
t = tm[idx]

# =====================================
# 2) Pan-Tompkins sampai R-peaks
# =====================================
bp = [5, 15]
bBP, aBP = butter(3, np.array(bp) / (Fs / 2), btype='bandpass')
ecg_f = filtfilt(bBP, aBP, ecg)

d_ecg = np.concatenate(([0], np.diff(ecg_f))) * Fs
sq_ecg = d_ecg ** 2

mwi_ms = 150
win = max(1, round((mwi_ms / 1000) * Fs))

# movmean MATLAB -> convolution/rolling mean
mwi = np.convolve(sq_ecg, np.ones(win) / win, mode='same')

thr = np.mean(mwi) + 0.5 * np.std(mwi)
minDist = round((200 / 1000) * Fs)

locs, _ = find_peaks(mwi, height=thr, distance=minDist)

search_win = round((100 / 1000) * Fs)
r_locs = np.zeros(len(locs), dtype=int)

for i, loc in enumerate(locs):
    L = max(0, loc - search_win)
    R = min(len(ecg_f), loc + search_win + 1)
    rr = np.argmax(ecg_f[L:R])
    r_locs[i] = L + rr

r_locs = np.unique(r_locs)
r_times = t[r_locs]

# =====================================
# 3) Q dan S peaks
# =====================================
qrs_half_ms = 60
qrs_half = round((qrs_half_ms / 1000) * Fs)

q_locs = np.zeros(len(r_locs), dtype=int)
s_locs = np.zeros(len(r_locs), dtype=int)

for i, r in enumerate(r_locs):
    # Q peak: minimum sebelum R
    Lq = max(0, r - qrs_half)
    Rq = r + 1
    iq = np.argmin(ecg_f[Lq:Rq])
    q_locs[i] = Lq + iq

    # S peak: minimum setelah R
    Ls = r
    Rs = min(len(ecg_f), r + qrs_half + 1)
    is_ = np.argmin(ecg_f[Ls:Rs])
    s_locs[i] = Ls + is_

# =====================================
# 4) FITUR 1: R-R interval + HR
# =====================================
RR = np.diff(r_times)      # detik
HR = 60 / RR if len(RR) > 0 else np.array([])

# =====================================
# 5) FITUR 2: Durasi QRS
# =====================================
q_times = t[q_locs]
s_times = t[s_locs]

QRS_dur = s_times - q_times
QRS_dur_ms = 1000 * QRS_dur

# =====================================
# 6) Tampilkan fitur
# =====================================
print("\n========= FITUR ECG (10 detik) =========")
print(f"Jumlah R-peaks = {len(r_locs)}")

print("\nR-peak times (s):")
print(r_times)

print("R-R intervals (s):")
print(RR)

print("Instantaneous HR (BPM):")
print(HR)

print("\nQ times (s):")
print(q_times)

print("S times (s):")
print(s_times)

print("QRS duration (s):")
print(QRS_dur)

if len(RR) > 0:
    print(f"Rata-rata RR (s)   = {np.mean(RR):.3f}")
    print(f"Rata-rata HR (BPM) = {np.mean(HR):.2f}")
else:
    print("Rata-rata RR (s)   = NaN")
    print("Rata-rata HR (BPM) = NaN")

print(f"Rata-rata QRS (s)  = {np.mean(QRS_dur):.3f}")
print("=======================================\n")

# =====================================
# 7) Plot Q-R-S
# =====================================
plt.figure(figsize=(12, 5))
plt.plot(t, ecg, 'b', label='ECG Signal')
plt.grid(True)

plt.plot(t[r_locs], ecg[r_locs], 'rv', markersize=7, markeredgewidth=1.2, label='R peaks')
plt.plot(t[q_locs], ecg[q_locs], 'bo', markersize=6, markeredgewidth=1.2, label='Q peaks')
plt.plot(t[s_locs], ecg[s_locs], 'gs', markersize=6, markeredgewidth=1.2, label='S peaks')

plt.title('Deteksi Kompleks QRS pada Sinyal ECG')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.legend(loc='upper right')
plt.xlim([0, dur])
plt.tight_layout()
plt.show()